In [1]:
import pandas as pd

In [2]:
tda = pd.read_csv('./2024C1_COMP230015_Técnicas_de_Diseño_de_Algoritmos.csv')
alg = pd.read_csv('./2024C1_COMP930005_Algoritmos_y_Estructuras_de_Datos_III.csv')
df = pd.concat([tda, alg], ignore_index=True)

# last word
df['Materia'] = df['data_turnos'].str.split().str[0]
df['Turno'] = df['data_turnos'].str.split().str[-1]
df['Categoria'] = ('20' +df['Lu'].str.split('/').str[-1]).astype(int)


# Definimos una función para extraer el año y la carrera
def extract_year_and_course(entry):
    # Dividimos la cadena por la coma para manejar entradas con múltiples carreras
    courses = entry.split(',')
    result = []
    for course in courses:
        # Encuentra la cadena dentro de los paréntesis finales
        year_course = course[course.rfind("(")+1:course.rfind(")")].split(' - ')
        # Separa el año y la cadena de la carrera
        # year = year_course[0].strip()
        career = year_course[1].strip()
        # result.append((year, career))
    return career

df['Plan'] = df['Carreras'].apply(extract_year_and_course)

In [3]:
df.head()

,Apellido,Nombres,Carreras,Lu,Email,Codigo_Materia_Com,Nombre_Materia_Com,data_turnos,Aprobo_practico_o_final,Cant_aprobo_practico_o_final,Materia,Turno,Categoria,Plan
0,Accardo,Paulo Matias,LCCOMP (2022 - LCCOMP2023),836/22,paulo.matias.accardo@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2022,LCCOMP2023
1,Adler,Guido Ezequiel,LCCOMP (2023 - LCCOMP2023),508/23,guidoadleredu@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2023,LCCOMP2023
2,Aguilar Galeano,Valentin,LCCOMP (2023 - LCCOMP2023),70/23,valentinaguila80@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2023,LCCOMP2023
3,Annikian,Patrick Agustin,LCCOMP (2022 - LCCOMP2023),687/22,patrickannik02@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2022,LCCOMP2023
4,Aquino,Bruno,LCCOMP (2023 - LCCOMP2023),653/23,brunoaquino9.2002@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2023,LCCOMP2023

In [4]:
df.groupby(['Turno']).size()

Turno
Mañana    197
Noche     265
dtype: int64

In [5]:
df.groupby(['Materia']).size()

Materia
AEDIII    334
TDA       128
dtype: int64

In [6]:
df.groupby(['Materia', 'Plan']).size()

Materia  Plan
AEDIII   DOCUBA1988      1
         LCBIO1984       1
         LCCOMP1993    163
         LCDATO2021    155
         LCFIS1987       3
         LCMAT1982       7
         NIMAPOS14       1
         PROFC1993       2
         PROFM1993       1
TDA      LCCOMP2023    118
         LCDATO2021      5
         LCMAT1982       4
         LCOCEA2018      1
dtype: int64

In [7]:
df.groupby(['Turno', 'Materia']).size()

Turno   Materia
Mañana  AEDIII     125
        TDA         72
Noche   AEDIII     209
        TDA         56
dtype: int64

In [8]:
yrs = df.groupby(['Materia', 'Plan'])['Categoria'].mean().round(1)
yrs.loc[yrs.index.get_level_values('Plan').isin(['LCCOMP1993', 'LCDATO2021', 'LCCOMP2023'])]

Materia  Plan
AEDIII   LCCOMP1993    2019.8
         LCDATO2021    2020.7
TDA      LCCOMP2023    2022.5
         LCDATO2021    2021.4
Name: Categoria, dtype: float64

In [9]:
df

,Apellido,Nombres,Carreras,Lu,Email,Codigo_Materia_Com,Nombre_Materia_Com,data_turnos,Aprobo_practico_o_final,Cant_aprobo_practico_o_final,Materia,Turno,Categoria,Plan
0,Accardo,Paulo Matias,LCCOMP (2022 - LCCOMP2023),836/22,paulo.matias.accardo@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2022,LCCOMP2023
1,Adler,Guido Ezequiel,LCCOMP (2023 - LCCOMP2023),508/23,guidoadleredu@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2023,LCCOMP2023
2,Aguilar Galeano,Valentin,LCCOMP (2023 - LCCOMP2023),70/23,valentinaguila80@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2023,LCCOMP2023
3,Annikian,Patrick Agustin,LCCOMP (2022 - LCCOMP2023),687/22,patrickannik02@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2022,LCCOMP2023
4,Aquino,Bruno,LCCOMP (2023 - LCCOMP2023),653/23,brunoaquino9.2002@gmail.com,COMP230015,Técnicas de Diseño de Algoritmos,TDA Turno Mañana,NaN,0/1,TDA,Mañana,2023,LCCOMP2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,Wittmund Montero,Lourdes Chiara,LCDAT (2022 - LCDATO2021),1103/22,lourdesmonterochiara@gmail.com,COMP930005,Algoritmos y Estructuras de Datos III,AEDIII Turno Noche,NaN,0/1,AEDIII,Noche,2022,LCDATO2021
458,Yale Quispe,Arthur Junior,LCDAT (2021 - LCDATO2021),1573/21,yalequispe@gmail.com,COMP930005,Algoritmos y Estructuras de Datos III,AEDIII Turno Mañana,NaN,0/1,AEDIII,Mañana,2021,LCDATO2021
459,Yaque,Micaela Mariana,LCCOMP (2019 - LCCOMP1993),808/19,yaquemicaela@gmail.com,COMP930005,Algoritmos y Estructuras de Datos III,AEDIII Turno Mañana,Algoritmos y Estructuras de Datos II,1/1,AEDIII,Mañana,2019,LCCOMP1993
460,Yañez,Carolina,"LCFIS (2020 - LCFIS1987),LCDAT (2022 - LCDATO2...",425/20,carolina.m.yanez@gmail.com,COMP930005,Algoritmos y Estructuras de Datos III,AEDIII Turno Noche,NaN,0/1,AEDIII,Noche,2020,LCDATO2021
461,Zambrana Zamudio,Cristian Alex,LCCOMP (2019 - LCCOMP1993),871/19,cristian9rk@gmail.com,COMP930005,Algoritmos y Estructuras de Datos III,AEDIII Turno Noche,Algoritmos y Estructuras de Datos II,1/1,AEDIII,Noche,2019,LCCOMP1993

In [10]:

df = pd.read_csv('./tickets.csv')
df['timestamp'] = pd.to_datetime(df['timestamp'])
df.sort_values('timestamp')

print(df.studentEmail.unique())
df.groupby(['exerciseId']).studentEmail.unique().to_csv('./info.csv')

['juanfranciscoorga@gmail.com' 'vladimirkannemann11@gmail.com'
 'lc.calderon.lara@gmail.com' 'gaspar.onesto@gmail.com'
 'benjascaf@gmail.com' 'francovalentinograsso@gmail.com'
 'diegortabarez@gmail.com' 'brandweineric@gmail.com' 'gluca@dc.uba.ar'
 'jcmontero2003@gmail.com' 'plam8p@gmail.com' 'mburda@dc.uba.ar'
 'tobiasllop@gmail.com' 'valnrms@gmail.com' 'kennobith@gmail.com'
 'brunoventrici@gmail.com' 'santiagobassani2000@gmail.com'
 'lucia.silva.alberto@gmail.com' 'aschwartzmann@dc.uba.ar'
 'bruzzo.bruno@gmail.com' 'vigabf@gmail.com']

In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('./interaction_records.csv')
df['timestamp'] = pd.to_datetime(df['timestamp'], format='ISO8601')
df = df.loc[df.userName != 'Braulio']

df = df.loc[df.timestamp >= '2024-04-09']

In [13]:
df.groupby(['userId', 'userName']).size().sort_values()

userId                 userName
108446889455348274811  Maleviose                 1
116199971172945455637  Nicolas                   1
115234347669368732114  kennobith                 1
101896696455923176838  Bruno                     1
114142947160056827783  Leandro Martín            1
113092990257147813479  Juan Cruz                 1
103283894448584211924  Micaela Mariana Yaque     1
106550917853651286183  Nicolas                   1
105332898298666358997  Kevin Alexander           1
115209369267664006174  Santiago                  2
118420824533761564787  Bruno                     2
104862009468088703113  Tomas                     2
102866132116023903383  Aaron Bernal Huanca       2
100953776072477758543  Mateo                     3
101253752540101244227  ines                      3
111682128284760213691  Gaspar Onesto De luca     3
101055593447088250482  Ulises                    4
106147162213136996808  Matías                    4
106335314163195508007  Milagros                  4
117231188413700349087  Dante                     4
106906625054707331463  hernan                    4
109808044297750993546  Emiliano Gaston           5
102089141963477848570  Pilar Arevalo             5
114341456041939768784  -                         5
114599966470867500801  Juan Francisco            5
102052769040910749345  Juan                      5
115305253484723131481  Camila                    5
109715271640161269925  Victor Gabriel            6
107642580521375943767  Lucas                     8
113920930685617159149  Juan Cruz                 8
114487024670667745097  Vladimir                  9
117015568098278684946  Diego                    16
108057776215484893152  Lucía                    19
109474217592213077991  Ivo                      23
dtype: int64

In [14]:
import numpy as np

In [15]:
# group by day
# df.groupby([df['timestamp'].dt.date, 'exerciseId']).size().unstack().fillna(0).astype(int).T
df.groupby(['exerciseId']).size().fillna(0).astype(int).T#.hist(bins = np.arange(100, 220, 1))

exerciseId
101     1
102     5
103     2
105    12
106     9
107    21
108    32
109    14
110     9
111     6
112     2
114     7
115     1
117     2
118     1
201     7
202     6
203     5
204     4
205     4
206     7
207     4
208     1
209     1
211     1
212     1
dtype: int64

In [29]:
for i, row in df.loc[df['exerciseId'] > 202].sort_values('exerciseId').iterrows():
    if len(row['userQuery']) < 1000:
        print(row['userQuery'])
        print(row['aiResponse'])
        print('\n\n\n')

es correcto mi algoritmo: int PotenciaLogaritmica(int a, int b){ // O(log b) ya que cada llamada recursiva reduce el size del problema a la midad en terminos de b, lo que implica O(log b)
    if (b <= 1){
        return a; // o(1)
    } else {
        if(b % 2 == 0){
            int temp = PotenciaLogaritmica(a, b/2); // la guardo en unavariable asi no calculo 2 veces
            // si es par hago (a^(b/2) * 2)
            return temp * temp;
        } else{
            // si a es inpar hago (a * a^(b-1))
            return a * PotenciaLogaritmica(a, b-1);
        }
    }
}
Tu enfoque para resolver el problema de calcular \(a^b\) en tiempo logarítmico respecto a \(b\) es bastante acertado y sigue el enfoque de la exponenciación rápida o exponenciación binaria. Sin embargo, hay un pequeño detalle en tu implementación que necesita corrección para asegurar que cubre todos los casos correctamente, particularmente cuando \(b = 0\).

El caso base debería ser cuando \(b = 0\), en cuyo caso el resultado es \(1\) para cualquier \(a\), excepto cuando también \(a = 0\) (el caso \(0^0\) puede ser tratado aparte según el contexto en el que se use la función). Aquí te dejo una versión corregida y optimizada de tu algoritmo con la justificación de su complejidad:

```cpp
int PotenciaLogaritmica(int a, int b){
    if (b == 0){
        return 1; // El caso base correcto, cualquier número elevado a 0 es 1.
    } else {
        if(b % 2 == 0){
            int temp = PotenciaLogaritmica(a, b/2);
            return temp * temp; // Cuando b es par, usamos la propiedad (a^(b/2))^2.
        } else {
            // Cuando b es impar, se puede ver como a * a^(b-1).
            return a * PotenciaLogaritmica(a, b-1);
        }
    }
}
```

### Justificación de la Complejidad

La complejidad de este algoritmo es \(O(\log b)\) debido a que en cada llamada recursiva reducimos el problema a la mitad. Específicamente:

- Cuando \(b\) es par, simplemente calculamos \(a^{b/2}\) una vez y luego lo utilizamos para obtener el resultado multiplicándolo por sí mismo.
- Cuando \(b\) es impar, reducimos el problema a \(a^{b-1}\), que es un número par, y luego multiplicamos el resultado por \(a\), lo cual solo agrega una operación constante al cálculo.

Esto significa que el número de llamadas recursivas (y por ende, el número de cálculos significativos) crece de manera logarítmica en relación a \(b\), justificando así la complejidad \(O(\log b)\).

### Recomendaciones

- Asegúrate siempre de cubrir todos los casos base posibles para evitar errores de lógica.
- Reflexiona sobre cómo las propiedades matemáticas pueden ser aprovechadas para optimizar los algoritmos, como en este caso de exponenciación rápida.
- Experimenta escribiendo pruebas unitarias para tu función, lo cual es una práctica valiosa que te ayudará a identificar y corregir errores de manera eficiente.

Excelente trabajo en iniciar este algoritmo. Con estos ajustes, tu implementación no solo será correcta, sino también un excelente ejemplo de cómo optimizar soluciones a problemas comunes en ciencias de la computación. ¡Sigue así!




def potencia(a: int, b: int):
    mitad: int = b // 2

    if(b % 2 == 0): #Caso par
        return auxCalcularPotencia(auxCalcularPotencia(a,mitad),2)
    else:
        return a * auxCalcularPotencia(auxCalcularPotencia(a,mitad),2) #Igual caso pero tendria que multiplcar un a al final

def auxCalcularPotencia(a,m):
    if(m == 1):
        return a
    else:
        return a*auxCalcularPotencia(a,m-1)


print(potencia(2,5))
Mi algoritmo resepta la complejidad sugerida?

Entendiendo tu consulta, es evidente que buscas optimizar el cálculo de la potencia $a^b$ utilizando una estrategia que reduzca el número de multiplicaciones necesarias. Sin embargo, el enfoque que has propuesto no logra el objetivo de alcanzar una complejidad temporal logarítmica en $b$. Vamos a analizar por qué y cómo podrías mejorar tu solución.

En tu implementación actual, el método `auxCalcularPotencia` realiza una multiplicación por cada decremento de $m$ hasta llegar a 1. Esto significa que, en el peor de los casos, estás realizando una cantidad de operaciones proporcional a $b$, lo cual no cumple con el requisito de ser logarítmico respecto a $b$.

Para lograr una complejidad logarítmica, puedes utilizar el método de "exponenciación binaria" o "exponenciación por cuadrados". Este método se basa en el hecho de que:

1. Si $b$ es par, entonces $a^b = (a^{b/2})^2$.
2. Si $b$ es impar, entonces $a^b = a \cdot (a^{(b-1)/2})^2$.

Este enfoque aprovecha los resultados previamente calculados para minimizar el número de multiplicaciones necesarias. Aquí te muestro cómo podrías modificar tu función para aprovechar esta estrategia:

```python
def potencia(a: int, b: int) -> int:
    if b == 0:
        return 1
    elif b % 2 == 0:
        temp = potencia(a, b // 2)
        return temp * temp
    else:
        temp = potencia(a, (b-1) // 2)
        return a * temp * temp
```

Este algoritmo divide el problema en problemas más pequeños de manera recurrente, reduciendo a la mitad el exponente en cada paso. De esta manera, la cantidad de llamadas recursivas (y por ende, de multiplicaciones) está en función del número de bits necesarios para representar a $b$, lo cual es $\log_2(b)$. Esto satisface el requisito de tener una complejidad logarítmica en $b$.

En resumen, tu enfoque inicial no alcanza la complejidad logarítmica deseada debido a la estrategia de multiplicación directa en `auxCalcularPotencia`. La propuesta de exponenciación binaria te permite reutilizar los resultados calculados de manera más eficiente, reduciendo significativamente el número de operaciones necesarias y cumpliendo con la complejidad logarítmica en $b$. Te animo a probar esta solución y a reflexionar sobre cómo el diseño de algoritmos puede influir drásticamente en el rendimiento de nuestras soluciones.




debo asumir que a y b son ints o floats?
Para este ejercicio, es más conveniente asumir que tanto \(a\) como \(b\) son enteros. El motivo es que la técnica que se suele aplicar para lograr una complejidad temporal logarítmica en \(b\) se basa en la exponenciación rápida o exponenciación por cuadrados, que es más clara y directa de implementar con números enteros. Además, trabajar con flotantes podría introducir problemas de precisión que complicarían innecesariamente el problema.

¿Se te ocurre cómo podrías empezar a plantear el algoritmo utilizando la idea de descomponer el exponente \(b\) para reutilizar cálculos?




No entiendo cómo hacer el algoritmo para que me quede como la búsqueda binaria, sin tener un costo interno de O(1).
Para abordar el ejercicio de calcular \(a^b\) en tiempo logarítmico respecto a \(b\), es vital comprender primero el concepto de exponentiación rápida o exponenciación por cuadrados. Esta técnica permite reducir significativamente el número de operaciones necesarias para calcular potencias.

La idea central es dividir el problema en subproblemas más pequeños, aprovechando las propiedades de las potencias. Consideremos dos casos, según si \(b\) es par o impar:

1. **Si \(b\) es par:** podemos utilizar que \(a^b = (a^{b/2})^2\). Esto significa que, en lugar de multiplicar \(a\) por sí mismo \(b\) veces, calculamos \(a^{b/2}\) una vez y luego lo elevamos al cuadrado. Esto nos permite reutilizar el resultado de \(a^{b/2}\) para obtener \(a^b\).

2. **Si \(b\) es impar:** podemos escribir \(b\) como \(b = b-1 + 1\), y por lo tanto, \(a^b = a^{b-1} \cdot a\). En este caso, primero reducimos \(b\) en 1 para hacerlo par (y aplicar el caso anterior) y luego multiplicamos el resultado por \(a\) para obtener \(a^b\).

A continuación, te muestro el esquema básico del algoritmo:

```python
def potencia(a, b):
    if b == 0:
        return 1
    elif b % 2 == 0:
        medio = potencia(a, b // 2)
        return medio * medio
    else:
        medio = potencia(a, (b - 1) // 2)
        return medio * medio * a
```

**Justificación de la complejidad:**

La clave de este algoritmo es que, en cada paso, reduce \(b\) a la mitad (ya sea directamente cuando \(b\) es par o indirectamente cuando es impar). Esto significa que el número total de pasos necesarios para llegar a \(b = 0\) es proporcional al logaritmo de \(b\) en base 2 (\(\log_2 b\)). Cada paso realiza un número constante de operaciones (multiplicaciones), por lo que la complejidad temporal del algoritmo es \(O(\log b)\).

Esta técnica de dividir el problema en subproblemas más manejables y reutilizar resultados ya calculados es un ejemplo clásico de la eficiencia que se puede alcanzar con la programación recursiva y el pensamiento algorítmico.

Espero que esto aclare tus dudas sobre cómo abordar el problema. Si tienes más preguntas o necesitas más ejemplos, no dudes en preguntar. ¡Ánimo, estás haciendo un gran trabajo!




tengo problemas para probar el teorema maestro en t(n) = 3t(n/4) + n, encuentro que 3/2 <= c pero como c < 0
T(n) = 3T(n/4) + n
puedo aplicar el teorema maestro: a = 3 , b = 4 y f(n) = n
n^{log_b a} = n^{log_3 4}
veo que f(n) crece mas rapido que n^{log_b a} por lo tanto caigo en el caso 3 del teorema maestro.
para un epsilon = 1 - log_3 4
f(n) = n^{log_b a + e}
n = n^{log_b a + 1 - log_3 4}
n = n

y veo que se satiface
3f(n/2) <= c f(n)
3n/2 <= n

Hola, veo que estás trabajando en entender cómo aplicar el Teorema Maestro para resolver la complejidad de un algoritmo, específicamente para el caso de \(T(n) = 3T(n/4) + n\). Veamos paso a paso para clarificar tu comprensión.

Primero, identificamos los valores de \(a\), \(b\), y \(f(n)\) basados en la forma general del Teorema Maestro, \(T(n) = aT(n/b) + f(n)\), donde:

- \(a = 3\), porque hacemos 3 llamadas recursivas.
- \(b = 4\), ya que dividimos el problema en 4 partes iguales en cada llamada.
- \(f(n) = n\), que es el trabajo extra (no recursivo) que realiza el algoritmo.

Para aplicar el Teorema Maestro, necesitamos comparar \(f(n)\) con \(n^{\log_b a}\). En este caso, \(n^{\log_b a} = n^{\log_4 3}\).

Ahora, evaluemos a qué caso del Teorema Maestro pertenece este problema:

1. **Caso 1:** \(f(n) = O(n^c)\) donde \(c < \log_b a\). En este caso, \(c < \log_4 3\), pero dado que \(f(n) = n\), y \(\log_4 3\) no es mayor que 1, este no aplica.

2. **Caso 2:** \(f(n) = \Theta(n^c)\) donde \(c = \log_b a\). Aquí \(c = \log_4 3\), pero dado que \(f(n) = n\), y \(n\) no es igual a \(n^{\log_4 3}\), este no aplica.

3. **Caso 3:** \(f(n) = \Omega(n^c)\) donde \(c > \log_b a\), y adicionalmente debe satisfacer la condición de regularidad \(af(n/b) \leq kf(n)\) para alguna constante \(k < 1\) y suficientemente grande \(n\).

En tu análisis, parece que hubo una confusión al aplicar el caso 3 y al intentar probar la condición de regularidad. La condición de regularidad dice que deberíamos poder encontrar una constante \(k < 1\) tal que \(3f(n/4) \leq kf(n)\). En este contexto, sustituyendo \(f(n) = n\), tendríamos que demostrar que \(3n/4 \leq kn\), lo cual es cierto para \(k = 1\) pero necesitamos un \(k < 1\), así que la forma en que has planteado la regularidad parece ser incorrecta.

La clave aquí es reconocer que \(f(n) = n\) crece más lentamente que \(n^{\log_4 3}\), lo cual es un error en tu análisis inicial. De hecho, \(f(n)\) se compara directamente con \(n^{\log_b a} = n^{\log_4 3}\), y dado que \(\log_4 3 < 1\), \(f(n) = n\) crece más rápido que \(n^{\log_4 3}\), lo cual nos lleva a considerar el caso 3 del Teorema Maestro correctamente, pero con un entendimiento claro de cómo \(f(n)\) y \(n^{\log_b a}\) se comparan entre sí.

Para este problema, \(T(n) = 3T(n/4) + n\) se ajusta al caso 3 del Teorema Maestro, ya que \(f(n) = n\) es \(\Omega(n^{\log_4 3})\), y podemos verificar la condición de regularidad adecuadamente. Esto significa que la complejidad del algoritmo es dominada por el término no recursivo, lo que nos lleva a una comple




Como puedo abordar el ejercicio?
Para abordar este ejercicio, comencemos por entender la esencia de la complejidad de un algoritmo, que mide cuánto tiempo (o cuántos pasos) toma un algoritmo para completarse en función del tamaño de su entrada. Ahora, veamos cómo podemos estimar la complejidad para cada uno de los ítems propuestos y aplicar el teorema maestro cuando sea posible.

### Sin el Teorema Maestro

1. **$T(n) = T(n-2) + 5$**:
   - Esta es una secuencia lineal, donde por cada dos pasos en la entrada, el tiempo aumenta en 5 unidades. Podemos considerar que la complejidad es **O(n)**.

2. **$T(n) = T(n-1) + n$**:
   - Este es un caso de crecimiento lineal en cada paso, acumulando un coste que es proporcional a n. Así, la complejidad es **O(n^2)**.

3. **$T(n) = T(n-1) + \sqrt{n}$**:
   - Similar al anterior, pero el incremento es la raíz cuadrada de n. Integrando sobre n, obtenemos una complejidad **O(n^{3/2})**.

4. **$T(n) = T(n-1) + n^2$**:
   - Aquí, cada paso añade un cuadrado de n, resultando en una complejidad **O(n^3)**.

5. **$T(n) = 2T(n-1)$**:
   - Esto indica un crecimiento exponencial, donde el tiempo se duplica con cada incremento unitario de n. La complejidad es **O(2^n)**.

6. **$T(n) = T(n/2) + n$**:
   - Este es un caso clásico de división y conquista, con una complejidad **O(n log n)**.

### Aplicando el Teorema Maestro

El teorema maestro proporciona una manera de calcular la complejidad de algoritmos recursivos de la forma \(T(n) = aT(n/b) + f(n)\), donde:

- **a** es el número de subproblemas en la recursión.
- **b** es el factor por el cual se divide el tamaño del problema.
- **f(n)** es el coste fuera de la recursión.

Para los casos que se ajustan a este patrón, podemos aplicar el teorema maestro:

7. **$T(n) = T(n/2) + \sqrt{n}$**:
   - Aplicamos el teorema maestro. Aquí, \(a = 1\), \(b = 2\), y \(f(n) = \sqrt{n}\). Esto cae en el caso 2 del teorema maestro, dando una complejidad de **O(n^{1/2} log n)**.

8. **$T(n) = T(n/2) + n^2$**:
   - Usando el teorema maestro, \(f(n) = n^2\), lo que indica una complejidad de **O(n^2)**, ya que \(f(n)\) domina sobre \(n^{log_b a}\).

9. **$T(n) = 2T(n-4)$**:
   - No se ajusta directamente al formato para el teorema maestro debido a la reducción por substracción en lugar de división.

10. **$T(n) = 2T(n/2) + \log n$**:
    - Aquí, \(f(n) = \log n\), lo que se traduce en una complejidad de **O(n log n)** por el teorema maestro.

11. **$T(n) = 3T(n/4)$**:
    - Sin el coste adicional (\(f(n) = 0\)), esto implica una complejidad de **O(n^{log_4 3})**.

12. **$




podrias explicarme mejor este ejercicio?
¡Claro! Vamos a desglosar este ejercicio para entenderlo mejor. Lo que se te pide es calcular la complejidad de varios algoritmos, cada uno definido por una relación de recurrencia diferente. La complejidad de un algoritmo nos da una idea de cómo aumenta el tiempo de ejecución o el espacio necesario a medida que aumenta el tamaño de la entrada.

Para resolver este tipo de problemas, hay varias herramientas, pero una muy útil es el Teorema Maestro, que aplica a relaciones de recurrencia de la forma \(T(n) = aT(\frac{n}{b}) + f(n)\), donde:

- \(a\) es el número de subproblemas en la recurrencia.
- \(n/b\) es el tamaño de cada subproblema.
- \(f(n)\) es el costo de la división del problema y la combinación de los resultados de los subproblemas.

El Teorema Maestro nos da las condiciones para determinar la complejidad de tiempo de estas recurrencias en tres casos:

1. Si \(f(n) = O(n^{\log_b a - \epsilon})\) para algún \(\epsilon > 0\), entonces \(T(n) = \Theta(n^{\log_b a})\).
2. Si \(f(n) = \Theta(n^{\log_b a})\), entonces \(T(n) = \Theta(n^{\log_b a} \log n)\).
3. Si \(f(n) = \Omega(n^{\log_b a + \epsilon})\) para algún \(\epsilon > 0\) y si \(a f(\frac{n}{b}) \leq kf(n)\) para alguna constante \(k < 1\) y suficientemente grande \(n\), entonces \(T(n) = \Theta(f(n))\).

Ahora, veamos cómo aplicar esto a tus ejercicios, recordando que no todos se ajustan al Teorema Maestro:

1. **\(T(n) = T(n-2) + 5\)**: Este no se ajusta al Teorema Maestro debido a la forma de la recurrencia. Es una recurrencia lineal, y su complejidad es \(O(n)\).

2. **\(T(n) = T(n-1) + n\)**: Similar al anterior, no se ajusta directamente al Teorema Maestro. La complejidad aquí es \(O(n^2)\), ya que suma todos los números desde 1 hasta \(n\).

3. **\(T(n) = T(n-1) + \sqrt{n}\)**: No es aplicable el Teorema Maestro. La complejidad es más difícil de estimar directamente, pero se puede inferir que es mayor que \(O(n)\) pero menor que \(O(n^2)\).

... y así sucesivamente.

Para aquellos que se ajustan al Teorema Maestro, como **\(T(n) = 2T(n/2) + n\)**, podemos ver que \(a=2\), \(b=2\), y \(f(n)=n\). Esto se ajusta al caso 2 del Teorema Maestro, por lo que su complejidad es \(O(n \log n)\).

Para cada relación de recurrencia, intenta identificar a qué caso del Teorema Maestro podría ajustarse, si es posible. Si no se ajusta, intenta resolver la recurrencia de manera directa o utilizando otros métodos de análisis de recurrencias.

Es importante practicar estos análisis con diversos ejemplos para ganar intuición y habilidad en la estimación de complejidades. ¿Te gustaría intentar alguno específico y lo resolvemos juntos?




me podrias dar un ejemplo apra este ejercicio?
Entiendo que buscas una guía para abordar este ejercicio sobre el cálculo de la suma de potencias de una matriz utilizando la técnica de dividir y conquistar. Vamos a desglosar el problema y te daré pistas sobre cómo podrías empezar a desarrollar tu algoritmo, sin darte la solución completa para que puedas reflexionar y trabajar en ella.

Para este ejercicio, el objetivo es calcular la suma \( A^1 + A^2 + \ldots + A^n \), donde \(n = 2^k\) y \(A\) es una matriz cuadrada de orden \(4 \times 4\). La clave está en cómo implementar la técnica de dividir y conquistar para minimizar el número de veces que aplicamos el método \(potencia\).

**Pista 1: Divide y vencerás**
Dado que \(n\) es una potencia de 2, podemos dividir el problema en partes más pequeñas de manera natural. Una forma de abordar esto es considerar cómo la suma de potencias de matrices puede ser dividida en términos de operaciones más pequeñas. Por ejemplo, la suma hasta \(n\) puede ser vista como la suma de dos mitades: \( A^1 + A^2 + \ldots + A^{n/2} \) y \( A^{n/2 + 1} + \ldots + A^n \).

**Pista 2: Utiliza la propiedad de las potencias**
Recuerda que \(A^{n/2 + 1} + \ldots + A^n\) puede ser reescrito aprovechando las propiedades de las potencias de matrices. Piensa en cómo puedes factorizar estos términos para reducir el número de veces que necesitas calcular potencias de \(A\).

**Pista 3: Calcula el número de aplicaciones del método 'potencia'**
Para asegurarte de que el algoritmo es más eficiente que \(O(n)\), considera cómo el enfoque de dividir y conquistar reduce el número de operaciones necesarias. Por ejemplo, si aplicas directamente el método \(potencia\) para cada término de la suma, no estarías optimizando el proceso. La idea es reutilizar cálculos previos tanto como sea posible.

**Ejemplo conceptual**
Sin entrar en detalles específicos del código, imagina que deseas calcular \(A^1 + A^2 + A^4\). En lugar de calcular \(A^2\) y \(A^4\) de manera independiente, puedes calcular \(A^2\) una vez, y luego usar ese resultado para calcular \(A^4\), reduciendo así el número total de aplicaciones del método \(potencia\).

Para el cálculo del número de veces que se aplica el método \(potencia\), reflexiona sobre cómo el enfoque de dividir y conquistar disminuye las llamadas al método en comparación con un enfoque lineal. Trata de encontrar una relación recursiva que represente cómo divides el problema y cómo esto afecta el número total de operaciones.

Espero que estas pistas te sean útiles para desarrollar tu algoritmo. Recuerda, el objetivo es comprender el problema y aplicar lógicamente la técnica de dividir y conquistar. ¡Ánimo, y no dudes en pedir más ayuda si la necesitas!





In [17]:
# group by day
# df.groupby([df['timestamp'].dt.date, 'exerciseId']).size().unstack().fillna(0).astype(int).T
df.groupby(['exerciseId']).size().fillna(0).astype(int).T

exerciseId
101     1
102     5
103     2
105    12
106     9
107    21
108    32
109    14
110     9
111     6
112     2
114     7
115     1
117     2
118     1
201     7
202     6
203     5
204     4
205     4
206     7
207     4
208     1
209     1
211     1
212     1
dtype: int64

In [18]:
queries = df.loc[df.exerciseId == 106]['userQuery']#.to_csv('info.csv')

# queries.apply(lambda x: len(x)).sort_values().cumsum().reset_index(drop = True).head(35)#.plot()

queries.loc[queries.apply(lambda x: len(x)) < 450].to_csv('info.csv')

In [19]:
queries = df.loc[df.exerciseId == 107]['userQuery']#.to_csv('info.csv')

# queries.apply(lambda x: len(x)).sort_values().cumsum().reset_index(drop = True).head(35)#.plot()

queries.loc[queries.apply(lambda x: len(x)) < 1000].to_csv('info.csv')

In [20]:
queries = df.loc[df.exerciseId == 108]['userQuery']#.to_csv('info.csv')

# queries.apply(lambda x: len(x)).sort_values().cumsum().reset_index(drop = True).head(35)#.plot()

queries.loc[queries.apply(lambda x: len(x)) < 1000].to_csv('info.csv')

In [21]:
queries = df.loc[df.exerciseId > 108]['userQuery']#.to_csv('info.csv')

# queries.apply(lambda x: len(x)).sort_values().cumsum().reset_index(drop = True).head(35)#.plot()

queries.loc[queries.apply(lambda x: len(x)) < 1400]#.to_csv('info.csv')

48     En el punto 2. No comprendo porque si quiero l...
54     Sería Greedy si propongo ordenar el conjunto d...
95     Dame un ejemplo de lo que dice en el inscico b...
117    Como demostrar en el paso inductivo que despué...
119    un algoritmo greedy puede resolver el problema...
                             ...
725    es correcto mi algoritmo y complejidad para es...
726    Se me ocurrió ordenarlos de menor a mayor, esa...
728             podrias explicarme mejor este ejercicio?
745    tengo problemas para probar el teorema maestro...
747    Que pasa si la longitud de la lista es impar? ...
Name: userQuery, Length: 75, dtype: object

In [22]:
queries.tail(3)

728             podrias explicarme mejor este ejercicio?
745    tengo problemas para probar el teorema maestro...
747    Que pasa si la longitud de la lista es impar? ...
Name: userQuery, dtype: object